version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
<<<<<<< HEAD
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
=======

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
>>>>>>> 3573f969c2acb5b0629179daceefb4b1f22f64bc
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
<<<<<<< HEAD
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
=======
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
>>>>>>> 3573f969c2acb5b0629179daceefb4b1f22f64bc
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
      - cadvisor
<<<<<<< HEAD
    networks:
      - monitoring
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./default:/etc/nginx/sites-available/default
    ports:
      - 80:80
      - 443:443
    networks:
      - monitoring
    depends_on:
      - grafana

networks:
  monitoring:
=======
>>>>>>> 3573f969c2acb5b0629179daceefb4b1f22f64bc
