version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
  grafana:
    image: grafana/grafana:10.2.6-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
      - cadvisor

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

    depends_on:
      - grafana

  grafana_auth:
    build: ./grafana_auth_mock
    container_name: grafana_auth
    ports:
      - 8083:8083

    depends_on:
      - nginx

    # loki promtail
  loki:
    image: grafana/loki:2.8.11-amd64
    container_name: loki
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.8.11-amd64
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml

  go_container_log_user1:
    build:
      context: ./go_container_user1
      labels:
        - "user_id=18d2e020-538d-449a-8e9c-02e4e5cf41111"
    container_name: go_container_api_user1
    ports:
      - 8231:8231

    logging:
      driver: loki
      options:
        loki-url: http://192.168.164.143:3100/loki/api/v1/push
        loki-external-labels: job=docker,container_name=go_container_api_user1,userId=18d2e020-538d-449a-8e9c-1111111
    # depends_on:
    #   - promtail

  go_container_log_user2:
    build:
      context: ./go_container_user2
      labels:
        - "user_id=18d2e020-538d-449a-8e9c-011212999"
    container_name: go_container_api_user2
    ports:
      - 8232:8232

    logging:
      driver: loki
      options:
        loki-url: http://192.168.164.143:3100/loki/api/v1/push

        loki-external-labels: job=docker,container_name=go_container_api_user2,userId=18d2e020-538d-449a-8e9c-011212999

    depends_on:
      - promtail
